// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUwvysw9xvS5eIgL5G_NXsgkr-kAegiAU',
    appId: '1:489753882869:web:bc12c7424d7e46ba7d55bc',
    messagingSenderId: '489753882869',
    projectId: 'fir-chatapp-4c2da',
    authDomain: 'fir-chatapp-4c2da.firebaseapp.com',
    storageBucket: 'fir-chatapp-4c2da.appspot.com',
    measurementId: 'G-T0MQ8J8T1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt_yntTsWEfIv15rbNnCw11BTFc-Qc5nQ',
    appId: '1:489753882869:android:8a36eaa4b9d021527d55bc',
    messagingSenderId: '489753882869',
    projectId: 'fir-chatapp-4c2da',
    storageBucket: 'fir-chatapp-4c2da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASMtXUoSNispblbAD2oW3w7w_0sRznjEQ',
    appId: '1:489753882869:ios:f0d8a63aed3f470d7d55bc',
    messagingSenderId: '489753882869',
    projectId: 'fir-chatapp-4c2da',
    storageBucket: 'fir-chatapp-4c2da.appspot.com',
    iosClientId: '489753882869-hj0cdti80cabi3eu5bsib2b4u7gppno4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
